### ISSUE TITLE
Incomplete Github Repo compare to YouTube Video

### ISSUE THREAD

**Issue by JicenJol** [vikrant65-byte/IPL-dataset-Analysis#2]
Hello Brother,

You have made good project on cricket.
However, while trying to follow the steps you outlined on YouTube, we discovered that 
some of the necessary resources were missing. Can you let us know the proper workflow 
of project from start to end. Currently, We are stuck at mounting. There were no specific 
notebook available for mounting. Can you put some light here.

For the clarification hereby attached image for your reference:
![Github OL](https://user-images.githubusercontent.com/128591172/226873337-3e932a08-0bbe-44f7-ace2-6ad8160ba876.png)
![Github YT](https://user-images.githubusercontent.com/128591172/226873344-8fdad877-4d36-4835-b5f3-db24ebfaf476.png)
 

Lots of Love from Russia to India.

**Comment by JicenJol** [comment]
Hello Brother,

There was one confusion, there were two people name Raut. Another User Named as Pravin Raut have
also worked on IPL Data Analytics & following his youtube video & came to your git repo by mistake.

Great Work Brother Carry On.

**Comment by vikrant65-byte** [comment]
Hey,

No worries brother !
